### ISSUE TITLE
Unable to determine Swift version for the following pods...

### ISSUE THREAD

**Issue by Arkangel12** [mcrovero/flutter_interactive_keyboard#4] opened 2020-04-10 15:59 UTC
i just add the plugin and try to run the app.

 [!] Unable to determine Swift version for the following pods:

    - `flutter_interactive_keyboard` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

thanks!

**Comment by david-shortman** [comment] 2020-05-01 05:15
The latest version of the code does not appear to be published to pub. You can try using the latest version published on GitHub using this in your `pubspec.yml`:
```yml
flutter_interactive_keyboard:
    git:
      url: https://github.com/mcrovero/flutter_interactive_keyboard.git
      ref: master
```

**Comment by david-shortman** [comment] 2020-05-25 02:19
[The latest version of the code has now been published to Pub](https://pub.dev/packages/flutter_interactive_keyboard#013). Closing this issue until the problem is reproduced in latest version.

**Closed as completed by david-shortman** 2020-05-25 02:19 UTC
