### ISSUE TITLE
Reference to missing flutter_interactive_keyboard-Swift.h

### ISSUE THREAD

**Issue by SamJakob** [mcrovero/flutter_interactive_keyboard#11] opened 2020-06-24 16:10 UTC
```
flutter_interactive_keyboard-0.1.3/ios/Classes/FlutterInteractiveKeyboardPlugin.m:2:9: fatal error: 'flutter_interactive_keyboard/flutter_interactive_keyboard-Swift.h' file not found
    #import <flutter_interactive_keyboard/flutter_interactive_keyboard-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by david-shortman** [comment] 2020-09-27 14:38
This issue is caused by errors in the development environment. Check out this answer on StackOverflow for help resolving this issue: https://stackoverflow.com/a/54791495

**Closed as completed** 2020-09-27 14:39 UTC
