### ISSUE TITLE
When using package, project not compiling

### ISSUE THREAD

**Issue by EdgarEscobedoHdz** [mcrovero/flutter_interactive_keyboard#3] opened 2020-01-20 17:08 UTC
I'm trying to use this package but when compiling I get the following:

```
    /Users/edgar/flutter/.pub-cache/git/flutter_interactive_keyboard-7fda19c541af180545418e15231a9163f2d7ab35/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:132:74: error: 'UIKeyboardWillShow' has been renamed to 'UIResponder.keyboardWillShowNotification'

​            let isKeyboardShowing = notification.name == NSNotification.Name.UIKeyboardWillShow

​                                                                             ^~~~~~~~~~~~~~~~~~

​                                                                             UIResponder.keyboardWillShowNotification

​    UIKit.NSNotification.Name:11:23: note: 'UIKeyboardWillShow' was obsoleted in Swift 4.2

​        public static let UIKeyboardWillShow: NSNotification.Name

​                          ^

​    /Users/edgar/flutter/.pub-cache/git/flutter_interactive_keyboard-7fda19c541af180545418e15231a9163f2d7ab35/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:135:47: error: 'UIKeyboardFrameEndUserInfoKey' has been renamed to 'UIResponder.keyboardFrameEndUserInfoKey'

​                    let keyboardFrame = (userInfo[UIKeyboardFrameEndUserInfoKey] as AnyObject).cgRectValue

​                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

​                                                  UIResponder.keyboardFrameEndUserInfoKey

​    UIKit.UIKeyboardFrameEndUserInfoKey:3:12: note: 'UIKeyboardFrameEndUserInfoKey' was obsoleted in Swift 4.2

​    public let UIKeyboardFrameEndUserInfoKey: String
```

Thank you in advance for your effort!

**Comment by david-shortman** [comment] 2020-05-01 05:16
The latest version of the code does not appear to be published to pub. You can try using the latest version published on GitHub using this in your `pubspec.yml`:
```yml
flutter_interactive_keyboard:
    git:
      url: https://github.com/mcrovero/flutter_interactive_keyboard.git
      ref: master
```

**Comment by david-shortman** [comment] 2020-05-25 02:18
[The latest version of the code has now been published to Pub](https://pub.dev/packages/flutter_interactive_keyboard#013). Closing this issue until the problem is reproduced in latest version.

**Closed as completed by david-shortman** 2020-05-25 02:18 UTC
