### ISSUE TITLE
Cannot build project when adding plugin to dependencies

### ISSUE THREAD

**Issue by Sandrichka22** [mcrovero/flutter_interactive_keyboard#7] opened 2020-05-14 13:06 UTC
When adding the:

`flutter_interactive_keyboard: ^0.1.1`

to dependencies, the build fails with the following error:
```

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_interactive_keyboard' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```

**Comment by david-shortman** [comment] 2020-05-18 02:05
The latest version of the code does is not published to pub. You can try using the latest version published on GitHub using this in your `pubspec.yml`:
```yml
flutter_interactive_keyboard:
    git:
      url: https://github.com/mcrovero/flutter_interactive_keyboard.git
      ref: master
```

**Comment by david-shortman** [comment] 2020-05-25 02:19
[The latest version of the code has now been published to Pub](https://pub.dev/packages/flutter_interactive_keyboard#013). Closing this issue until the problem is reproduced in latest version.

**Closed as completed by david-shortman** 2020-05-25 02:19 UTC
